#!/bin/bash

yum update -y
yum install -y git python3 at

# Instalar GitHub CLI
yum install -y yum-utils
yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
yum install -y gh

# Habilitar o serviço atd (necessário para agendamento com 'at')
systemctl enable atd
systemctl start atd

# Clonar projeto
cd /home/ec2-user
git clone https://github.com/alerabello/sistema-de-locadora.git
cd sistema-de-locadora

# Criar venv, ativar e instalar pacotes
python3 -m venv venv
source venv/bin/activate
python3 -m pip install --upgrade pip
pip install -r requirements.txt

# Criar banco e admin
python3 run.py & sleep 5 && pkill -f run.py
python3 create_admin.py

# Criar o serviço systemd
cat <<EOF > /etc/systemd/system/flaskapp.service
[Unit]
Description=Flask Locadora App
After=network.target

[Service]
User=ec2-user
WorkingDirectory=/home/ec2-user/sistema-de-locadora
Environment="FLASK_APP=run.py"
Environment="PATH=/home/ec2-user/sistema-de-locadora/venv/bin"
ExecStart=/home/ec2-user/sistema-de-locadora/venv/bin/flask run --host=0.0.0.0 --port=5000
Restart=always

[Install]
WantedBy=multi-user.target
EOF

# Permissões para o banco SQLite
chmod -R 775 /home/ec2-user/sistema-de-locadora/instance/
chown -R ec2-user:ec2-user /home/ec2-user/sistema-de-locadora/instance/

# Criar admin se não existir
python3 create_admin.py

# Agendar ativação via 'at' (1 minuto após o boot)
echo "systemctl daemon-reexec && systemctl daemon-reload && systemctl enable flaskapp && systemctl start flaskapp" | at now + 1 minute